language: node_js

before_script:
- npm run prod

script:
  - echo All tests pass, yay!

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
